name: Push www/dist
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Push www/dist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: www/dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
